apiVersion: v1
kind: Secret

metadata:
  name: {{ include "localshop.fullname" . }}-secrets
  labels:
{{ include "localshop.chartlabels" . | indent 4 }}

type: Opaque

data:
  # example of random
  # randomexample: {{ default .Values.localshop.randomExample (randAlphaNum 32) | b64enc | quote }}

